# TODO remove the volumes, switch to an image for the build, copy to both nginx and php container
# from there

version: '3.1'
volumes:
     js-files:
services:
    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './public/data/:/application/public/data'
            - './public/index.php:/application/public/index.php'
            - 'js-files:/application/public/build'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '37000:80'

    php-fpm:
        build: ./
        working_dir: /application
        image: manulera/yeastdatabase_php
        volumes:
            - './public/data/:/application/public/data'
            - './public/index.php:/application/public/index.php'
            - 'js-files:/application/public/build'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
