# TODO remove the volumes, switch to an image for the build, copy to both nginx and php container
# from there

version: '3.1'
services:

  yeastdatabase:
      image: manulera/yeastdatabase_php
      ports:
        - "8000:8000"
