# TODO remove the volumes, switch to an image for the build, copy to both nginx and php container
# from there

version: '3.1'
services:

  yeastdatabase:
      image: manulera/yeastdatabase_php
      volumes:
      # This ensures that the database is not lost when restarting the container
        - ./example.db:/application/var/data.db
      ports:
        - "8000:8000"
